apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ include "circuit-breaker.namespace" . }}
  labels:
    {{- include "circuit-breaker.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    {{- include "circuit-breaker.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
